---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/code-eg/flux-get-started
    ref: master
    path: charts/ghost
  values:
    image:
      repository: bitnami/ghost
      tag: latest
    ghostPort: 8080
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
      port: 8080
    mariadb:
      master:
        persistence:
          enabled: false
    ingress:
      ## Set to true to enable ingress record generation
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip