---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: httpd
  namespace: demo
spec:
  releaseName: httpd
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami/apache
    version: 7.4.0

  values:
    usePassword: true
    image:
      repository: bitnami/apache
      tag: latest
    service:
      type: ClusterIP
    ingress:
      ## Set to true to enable ingress record generation
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip